global using Todos.Data.Entities;
global using Microsoft.EntityFrameworkCore;
global using System.Linq.Expressions;
global using System.Collections.Generic;
global using System.Threading;
global using AutoMapper;
global using System.ComponentModel.DataAnnotations;
global using System.ComponentModel.DataAnnotations.Schema;
global using System.Linq;
global using TodoTasks = Todos.Data.Entities.TodoTasks;