global using Microsoft.EntityFrameworkCore;
global using Todos.Data.Contexts;
global using Todos.Data.Entities;
global using System.Collections.Generic;
global using System.Threading;
global using System.Linq.Expressions;
global using AutoMapper;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Configuration;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;